config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get root to: "teams#index"
  resources :teams, except: :destroy
  resources :users, only: [:show, :destroy]
  resources :users do
    member do
      get "detail"
    end
  end
  resources :menus, except: [:index]
  resources :hiits, except: [:index]
  resources :groups, except: [:index]
  resources :hiits do
    resources :groups do
      collection do
        get "new_restricted"
      end
    end
    resources :user_hiits, only: [:create]
  end
  resources :user do
    resources :user_hiits, only: [:index]
  end
end

app/models/user_hiit.rb
class UserHiit < ApplicationRecord
  belongs_to :user
  belongs_to :hiit
  validates :done_dates, presence: true
end

app/controllers/user_hiits_controller.rb
class UserHiitsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @user = User.find(params[:user_id])
    unless user_signed_in? && (current_user.admin? || current_user.id.to_s == params[:user_id])
      redirect_to root_path
    end

    @today_hiit_for_user = set_today_hiit_for_user
  end

  def create
    if UserHiit.exists?(user_id: current_user.id, hiit_id: params[:hiit_id], done_dates: Date.today)
      UserHiit.where(user_id: current_user.id, hiit_id: params[:hiit_id], done_dates: Date.today).each do |user_hiit|
        user_hiit.destroy
      end
    else
      UserHiit.create(user_id: current_user.id, hiit_id: params[:hiit_id], done_dates: Date.today)
    end
  end

end

app/helpers/user_hiits_helper.rb
module UserHiitsHelper
end

app/views/user_hiits/index.html.erb
<main>
  <%= image_tag "rest.png", class:"img-fluid", id:"rest_image", style:"display: none;" %>
  <%= image_tag "finish.png", class:"img_fluid", id:"finish_image", style:"display: none;" %>
  <%= audio_tag("countdown.mp3", id:"countdownAudio") %>
  <%= audio_tag("finish.mp3", id:"finishAudio") %>
  <h1 class="shared-title mx-0"><%= link_to @user.name, user_path(@user), class:"text-dark text-decoration-none" %>さんの本日の予定</h1>

  
  <div class="card mb-3">  
    <div class="text-center card-header"><span class="badge bg-secondary" id="cycle_count">0</span><span id="menu_name">種目名</span></div>
    <div class="w-50 align-self-center d-flex align-items-center" id="card-image-container">
      <%= image_tag "junbi.png", class:"img-fluid", id:"ready_image" %>
    </div>
    <div id="progress-area"></div>
    <div class="text-center card-footer">残り<span id="time-area">--</span>秒</div>
  </div>
  

  <% if @today_hiit_for_user.any? %>
    <% @today_hiit_for_user.each do |hiit| %>
      <div class="card shadow-sm container mb-3">
        <div class="card-header row row-cols-1 row-cols-sm-2">
          <div class="col text-center d-flex justify-content-between align-items-center">
            <% if UserHiit.exists?(hiit_id: hiit.id, user_id: @user.id, done_dates: Date.today) %>
              <span class="badge bg-dark completed">実施済み!!</span>
            <% else %>
              <span class="badge bg-dark completed">未実施</span>
            <% end %>
            <%= link_to hiit.name, hiit_path(hiit), class:"btn text-secondary mb-0 fs-3 hiit_name", id:"hiit_name_#{hiit.id}" %>
          </div>
          <div class="col d-flex justify-content-around align-items-center">
            <% if user_signed_in? && @user.id == current_user.id %>
              <%= link_to "更新する", hiit_user_hiits_path(hiit), method: :post, class:"btn text-secondary mb-0 p-0 hiit-complete", id:"#{hiit.id}" %>
              <button class="timer btn btn-outline-secondary mb-0" id="timer_<%= hiit.id %>">時間を測る</button>
            <% end %>
          </div>
        </div>
        <div class="row row-cols-1 row-cols-sm-2 border-bottom border-bottom-light mb-2">
          <div class="col text-center py-2 active_time" id="active_time_<%= hiit.id %>">1種目あたりの時間：<%= hiit.active_time %></div>
          <div class="col text-center py-2 rest_time" id="rest_time_<%= hiit.id %>">休憩時間：<%= hiit.rest_time %></div>
        </div>
        <div class="row row-cols-2 row-cols-sm-3 row-cols-md-4">
          <% hiit.menu_hiits.length.times do |i| %>

            <div class="cols text-center">
              <div class="card my-2">
                <div class="card-header"><%= "#{i + 1}種目目" %></div>
              
                    <%= link_to menu_path(hiit.menu_hiits[i].menu), class:"text-secondary btn mb-0 text-center" do %>
                      <div class="card-body d-flex align-items-center p-0 justify-content-center" style="height: 150px;"><%= image_tag hiit.menu_hiits[i].menu.icon.variant(resize: "150 x 150"), class:"img-fluid" %></div>
                      <div class="card-footer text-truncate"><%= "#{hiit.menu_hiits[i].menu.name}" %></div>
                    <% end %>
                
                </div>
              </div>

          <% end %>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="alert alert-light rounded-0 border-0 text-center">本日の予定はありません</div>
  <% end %>

  <div class="link-container mx-0">
    <%= link_to "自分のページに戻る", user_path(current_user), class:"btn text-secondary mb-0" %>
    <%= link_to "チームのページに戻る", team_path(current_user.team), class:"btn text-secondary mb-0" %>
    <% if user_signed_in? && current_user.admin? %>
      <%= link_to "この選手のページに戻る", detail_user_path(@user), class:"btn text-secondary mb-0" %>
    <% end %>
  </div>

</main>