config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get root to: "teams#index"
  resources :teams, except: :destroy
  resources :users, only: [:show, :destroy]
  resources :users do
    member do
      get "detail"
    end
  end
  resources :menus, except: [:index]
  resources :hiits, except: [:index]
  resources :groups, except: [:index]
  resources :hiits do
    resources :groups do
      collection do
        get "new_restricted"
      end
    end
    resources :user_hiits, only: [:create]
  end
  resources :user do
    resources :user_hiits, only: [:index]
  end
end

app/models/hiit.rb
class Hiit < ApplicationRecord
  belongs_to :team
  has_many :user_hiits, dependent: :destroy
  has_many :users, through: :user_hiits
  has_many :menu_hiits, dependent: :destroy
  has_many :menus, through: :menu_hiits
  has_many :hiit_dates, dependent: :destroy
  has_one :group
  # with_options presence: true do
   # validates :name
   # validates :date
   # validates :active_time, format: { with: /\A[0-9]{2}[分秒]\z/ }
   # validates :rest_time, format: { with: /\A[0-9]{2}[分秒]\z/ }
  # end
end 

app/controllers/hiits_controller.rb
class HiitsController < ApplicationController
  before_action :admin_user?, only: [:create, :new, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :show]
  before_action :set_team, only: [:create, :edit, :destroy]
  before_action :set_hiit, only: [:show, :edit, :update, :destroy]
  before_action :set_messages, only: [:show, :destroy]
  def new
    @hiit_menu_hiit = HiitMenuHiit.new
  end
  
  def create
    @hiit_menu_hiit = HiitMenuHiit.new(hiit_params)
    if @hiit_menu_hiit.valid?
      @hiit_menu_hiit.save
      redirect_to team_path(@team)
    else
      render :new
    end
  end

  def show
    @menus = set_menus_of_hiit
    @wday_list = set_hiit_dates
  end

  def edit
    date = set_hiit_dates
    menu_ids = set_menu_ids_of_hiit
    @hiit_menu_hiit = HiitMenuHiit.new(name: @hiit.name, active_time: @hiit.active_time, rest_time: @hiit.rest_time, menu_ids: menu_ids, date: date, team_id: @hiit.team.id)
  end

  def update
    id = params[:id]
    @hiit_menu_hiit = HiitMenuHiit.new(hiit_params)
    if @hiit_menu_hiit.valid?
      @hiit_menu_hiit.update(id)
      redirect_to hiit_path(@hiit)
    else
      render :edit
    end
  end

  def destroy
    if Group.exists?(hiit_id: @hiit.id)
      @messages << "Since group using this hiit exists, this hiit can't be deleted"
      @menus = set_menus_of_hiit
      @wday_list = set_hiit_dates
      render :show
    else
      @hiit.destroy
      redirect_to team_path(@team)
    end
    
  end


  private
  def hiit_params
    params.require(:hiit_menu_hiit).permit(:name, :active_time, :rest_time, menu_ids: [], date: []).merge(team_id: current_user.team.id)
  end

  def set_team
    @team = current_user.team
  end

  def set_menus_of_hiit
    @menus = []
    @hiit.menu_hiits.each do |menu_hiit|
      @menus << menu_hiit.menu
    end
    return @menus
  end

  def set_menu_ids_of_hiit
    @menu_ids = []
    @menus = set_menus_of_hiit
    @menus.each do |menu|
      @menu_ids << menu.id
    end
    return @menu_ids
  end

  def set_hiit_dates
    @hiit_dates = []
    @hiit.hiit_dates.each do |hiit_date|
      @hiit_dates << hiit_date.date
    end
    return @hiit_dates
  end

  def set_hiit
    @hiit = Hiit.find(params[:id])
  end

end

app/helpers/hiits_helper.rb
module HiitsHelper
end

app/views/hiits/edit.html.erb
<main>
  <%= render "shared/error_messages", model: @hiit_menu_hiit %>
  <div class="menu-detail">
    <%= form_with model: @hiit_menu_hiit, url: "/hiits/#{@hiit.id}", method: :patch, local: true do |f| %>
    <div class="form-group">
      <%= f.label :name, "HIITの名前" %>
      <%= f.text_field :name, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :active_time, "1種目あたりの時間" %><i>(「（半角数字）秒または分」という形で入力してください)</i>
      <%= f.text_field :active_time, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :rest_time, "休憩時間" %><i>(「（半角数字）秒または分」という形で入力してください)</i>
      <%= f.text_field :rest_time, class:"form-control" %>
    </div>
    <div>
      <div><span  class="fs-4">実施日</span><br>(このHIITを実施する曜日に全てチェックを入れてください)</div>
      <%= f.collection_check_boxes(:date, Wday.all, :id, :name, include_hidden: false, checked: @hiit_menu_hiit.date) do |b| %>
        <div class="form-group form-check form-check-inline"><%= b.label {b.check_box + b.text} %></div>
      <% end %>
    </div>
    <div>このHIITで行う種目を選択してください</div>
    <div class="form-group">
      <% 8.times do |i| %>
          <%= "#{i + 1}番目の種目" %><select name="hiit_menu_hiit[menu_ids][]" class="form-control">
            <option value="0">---</option>
            <% current_user.team.menus.each do |menu| %>
              <option value='<%= "#{menu.id}" %>'><%= menu.name %></option>
            <% end %>
          </select>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.submit "HIITを編集する",class:"btn bg-light form-control" %>
      <div class="d-flex flex-column flex-sm-row justify-content-sm-around">
        <%= link_to "HIITのページに戻る", hiit_path(@hiit), class:"btn text-secondary mb-0" %>
        <%= link_to "チームのページに戻る", team_path(current_user.team), class:"btn text-secondary mb-0" %>
      </div>
    </div>
    <% end %>
  </div>
</main>

app/views/hiits/new.html.erb
<main>
  <div class="bg-light text-center fs-3 py-2">新しいHIITの作成画面です</div>
  <%= render "shared/error_messages", model: @hiit_menu_hiit %>
  <div class="menu-detail">
    <%= form_with model: @hiit_menu_hiit, url: hiits_path, local: true do |f| %>
    <div class="form-grop">
      <%= f.label :name, "HIITの名前" %>
      <%= f.text_field :name, class:"form-control" %>
    </div>
    <div class="form-grop">
      <%= f.label :active_time, "1種目あたりの時間" %><i>(「（半角数字）秒または分」という形で入力してください)</i>
      <%= f.text_field :active_time, class:"form-control" %>
    </div>
    <div class="form-grop">
      <%= f.label :rest_time, "休憩時間" %><i>(「（半角数字）秒または分」という形で入力してください)</i>
      <%= f.text_field :rest_time, class:"form-control" %>
    </div>

    <div>
      <div><span  class="fs-4">実施日</span><br>(このHIITを実施する曜日に全てチェックを入れてください)</div>
      <%= f.collection_check_boxes(:date, Wday.all, :id, :name, include_hidden: false) do |b| %>
        <div class="form-group form-check form-check-inline"><%= b.label {b.check_box + b.text} %></div>
      <% end %>
    </div>

    <div class="form-grop">
      <% 8.times do |i| %>
        <%= "#{i + 1}番目の種目" %><select name="hiit_menu_hiit[menu_ids][]" class="form-control">
          <option>---</option>
          <% current_user.team.menus.each do |menu| %>
            <option value='<%= "#{menu.id}" %>'><%= menu.name %></option>
          <% end %>
        </select>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.submit "HIITを登録する", class:"btn form-control text-secondary bg-light" %>
      <div class="lower-link">
        <button class="form-control btn bg-light"><%= link_to "チームのページに戻る", team_path(current_user.team), class:"text-secondary text-decoration-none m-0" %></div>
      </div>
    </div>
    <% end %>
  </div>
</main>

app/views/hiits/show.html.erb
<main>
  <% if @messages.any? %>
    <% @messages.each do |message| %>
      <div class="error-message">
        <%= message %>
      </div>
    <% end %>
  <% end %>

  <% group = @hiit.group %>

  <div class="card mb-3">
    <div class="card-header text-center">
      <%= link_to @hiit.name, hiit_path(@hiit), class:"text-secondary fs-3 text-decoration-none" %>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-12 col-sm-6 py-2 text-center">
          1種目あたりの時間：<%= @hiit.active_time %>
        </div>
        <div class="col-12 col-sm-6 py-2 text-center">
          休憩時間：<%= @hiit.rest_time %>
        </div>
      </div>
      <div class="row py-2">
        <div class="col-12 col-md-4 text-md-center">このHIITを行う曜日</div>
        <div class="col-12 col-md-8 text-end text-md-center">
          <% 7.times do |i| %>
            <% if @wday_list.include?(i) %>
              <span class="badge bg-secondary mx-2"><%= Wday.find(i).name %></span>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="text-center bg-light py-2">
        このHIITで行う種目
      </div>
      <div class="container">
        <div class="row">
          <% @menus.length.times do |i|%>
            <div class="col-12 col-sm-6 col-md-4 col-lg-3">
              <div class="card my-2">
                <%= link_to menu_path(@menus[i]), class:"text-decoration-none p-0 text-center" do %>
                  <div class="card-header text-center text-secondary"><%= "#{(i + 1)}種目目" %></div>
                  <div class="card-image-container justify-content-center d-flex align-items-center mx-auto" style="width: 150px; height: 150px;"><%= image_tag @menus[i].icon.variant(resize:"150 x 150"), class:"img-fluid" %></div>
                  <div class="card-footer text-center text-secondary"><%= @menus[i].name %></div>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <div class="text-center bg-light py-2">このHIITに取り組んでいるグループ</div>
        <% if @hiit.group != nil %>
          <div class="row">
            <div class="col-4 text-center py-2">グループ名</div>
            <div class="col-8 text-center py-2">所属している選手一覧</div>
          </div>
          <div class="row">
            <div class="col-4 d-flex align-items-center justify-content-center">
              <%= link_to group.name, group_path(group), class:"text-secondary text-decoration-none" %>
            </div>
            <% if group.user_groups.any? %>
              <div class="col-8 d-flex flex-wrap align-items-center justify-content-center">
                <% group.user_groups.each do |user_group| %>
                  <% if user_signed_in? && current_user.id == user_group.user.id %>
                    <div><%= link_to user_group.user.name, user_path(user_group.user), class:"text-secondary text-decoration-none" %></div>
                  <% elsif user_signed_in? && current_user.admin? %>
                    <div><%= link_to user_group.user.name, detail_user_path(user_group.user), class:"text-secondary text-decoration-none" %></div>
                  <% elsif user_signed_in? %>
                    <div><%= user_group.user.name%></div>
                  <% end %>
                <% end %>
              </div>
            <% else %>
            <div class="col-8">
              このグループに所属している選手はいません
            </div>
            <% end %>
          </div>
        <% else %>
          <div>このHIITに取り組んでいるグループはありません</div>
        <% end %>
      </div>
    </div>
  </div>



  <% if user_signed_in? && current_user.admin? && @hiit.group == nil %>
    <div class="link-container">
      <%= link_to "このHIITでグループを作成する", new_restricted_hiit_groups_path(@hiit), class:"text-secondary btn" %>
    </div>  
  <% end %>
  
  <div class="d-flex justify-content-center flex-wrap">
    <% if user_signed_in? && current_user.admin? %>
      <%= link_to "HIITを編集する", edit_hiit_path(@hiit), class:"text-secondary btn" %>
      <%= link_to "HIITを削除する", hiit_path(@hiit), method: :delete, class:"text-secondary btn" %>
      <%= link_to "HIITを作成する", new_hiit_path, class:"text-secondary btn" %>
    <% end %>
      <%= link_to "チームのページに戻る", team_path(@hiit.team), class:"text-secondary btn" %>
      <%= link_to "自分のページに戻る", root_path, class:"text-secondary btn" %>
    </div>
  
</main>