config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get root to: "teams#index"
  resources :teams, except: :destroy
  resources :users, only: [:show, :destroy]
  resources :users do
    member do
      get "detail"
    end
  end
  resources :menus, except: [:index]
  resources :hiits, except: [:index]
  resources :groups, except: [:index]
  resources :hiits do
    resources :groups do
      collection do
        get "new_restricted"
      end
    end
    resources :user_hiits, only: [:create]
  end
  resources :user do
    resources :user_hiits, only: [:index]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  belongs_to :team
  has_many :user_hiits, dependent: :destroy
  has_many :hiits, through: :user_hiits
  has_many :user_groups, dependent: :destroy
  has_many :groups, through: :user_groups
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_team, only: [:detail], if: :user_signed_in?
  before_action :set_user, only: [:detail, :destroy, :show]
  before_action :admin_user?, only: [:detail, :destroy]
  before_action :set_messages, only: [:show, :detail, :destroy]
  before_action :authenticate_user!
  def detail
    @hiit_for_user = set_hiit_for_user
  end

  def destroy
    lonely_groups = check_lonely_group
    if @lonely_groups.length >= 1
      @messages << "Since group containing this user exists, this user can't be deleted"
      @today_hiit_for_user = set_today_hiit_for_user
      @team = set_team
      render :show
    else
      @user.destroy
      @team = current_user.team
      @groups = current_user.groups
      @today_hiit_for__user = set_today_hiit_for_user
      redirect_to team_path(current_user.team)
    end
  end

  def show
    if user_signed_in? && current_user.id != @user.id && !(current_user.admin?)
      redirect_to root_path
    end

    @today_hiit_for_user = set_today_hiit_for_user
  end

  private
  def set_team
    @team = current_user.team
  end

  def set_user
    @user = User.find(params[:id])
  end

  def set_hiit_for_user
    @group_for_user = []
    UserGroup.all.each do |user_group|
      if user_group.user_id == @user.id
        @group_for_user << user_group.group
      end
    end

    @hiit_for_user = []
    @group_for_user.each do |group_for_user|
      @hiit_for_user << group_for_user.hiit
    end
    return @hiit_for_user
  end
end


def check_lonely_group
  @groups_of_user = []
  UserGroup.where(user_id: @user.id).each do |group_user|
    @groups_of_user << group_user.group
  end
  @lonely_groups = []
  @groups_of_user.each do |group|
    if UserGroup.where(group_id: group.id).length == 1
      @lonely_groups << group
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/detail.html.erb
<main>
  <h1 class="shared-title"><%= @user.name %>さんの今週の予定です</h1>
  <div class="weekly-menu-container">
    <% 7.times do |i| %>
      <div class="daily-menu-container">
        <div class="container-except-today">
          <div class="date-container">
            <%= (Date.today - 3 + i).strftime('%m/%d') %>
            <% day = (Date.today + i - 3).wday %>
            <%= "(#{(Wday.find(day).name).slice(0)})" %>
          </div>

        <% if @hiit_for_user.any? %>
          <% 
            that_day_hiit_for_user = []
            @hiit_for_user.each do |hiit_for_user|
              if HiitDate.exists?(hiit_id: hiit_for_user.id, date: day)
                HiitDate.where(hiit_id: hiit_for_user.id, date: day).each do |hiit_date|
                  that_day_hiit_for_user << hiit_date.hiit
                end
              end
            end
          %>
          <% if that_day_hiit_for_user.length > 4 %>
            <% 3.times do |j| %>
              <div class="todays-hiit-container">
                <% if UserHiit.exists?(user_id: @user.id, hiit_id: that_day_hiit_for_user[j].id, done_dates: (Date.today - 3 + i)) %>
                  ✅
                <% else %>
                  ❌
                <% end %>
                <%= link_to that_day_hiit_for_user[j].name, hiit_path(that_day_hiit_for_user[j]) %>
              </div>
            <% end %>
            <div class="todays-hiit-container">
                <% if UserHiit.exists?(user_id: @user.id, hiit_id: that_day_hiit_for_user[3].id, done_dates: (Date.today - 3 + i)) %>
                  ✅
                <% else %>
                  ❌
                <% end %>
                <%= link_to that_day_hiit_for_user[3].name, hiit_path(that_day_hiit_for_user[3]),class:"btn btn-link text-secondary mb-0" %> ...
              </div>
          <% elsif @hiit_for_user.any? %>
            <% @hiit_for_user.each do |hiit_for_user| %>
              <% if HiitDate.exists?(hiit_id: hiit_for_user.id, date: day) %>
                <div class="todays-hiit-container">
                  <% if UserHiit.exists?(user_id: @user.id, hiit_id: hiit_for_user.id, done_dates: (Date.today - 3 + i)) %>
                    ✅
                  <% else %>
                    ❌
                  <% end %>
                  <%= link_to hiit_for_user.name, hiit_path(hiit_for_user),class:"btn btn-link text-secondary mb-0" %>
                </div>
              <% end %>
            <% end %>
          <% end %>
        <% end %>

        </div>
        <% if i == 3 %>
          <div class="link-to-today">
            <%= link_to "今日の予定を見る", user_user_hiits_path(@user),class:"btn btn-link text-secondary mb-0 px-1" %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <% if current_user.admin? %>
    <div class="link-container">
      <%= link_to "#{@user.name}の詳細を見る", user_path(@user), class:"text-secondary" %>
      <%= link_to "チームのページに戻る", team_path(@team), class:"text-secondary" %>
    </div>
  <% end %>
</main>

app/views/users/index.html.erb
<h1><%= @user.name %>のトレーニングメニュー</h1>
<div class="weekly-menu-container">
  <% 7.times do %>
    <div class="daily-menu-container">
      1日分のトレーニングメニュー
    </div>
  <% end %>
</div>
<% if current_user.admin? %>
<div><%= link_to "#{@user.name}を削除する", user_path(@user), method: :delete %></div>
<div><%= link_to "チームのページに戻る", team_path(@team) %></div>
<% end %>

app/views/users/show.html.erb
<main>
  <% if @messages.any? %>
    <% @messages.each do |message| %>
      <div class="error-message">
        <%= message %>
      </div>
    <% end %>
  <% end %>
  <h1 class="shared-title mx-0"><%= "#{@user.name}さんの詳細ページです" %></h1>


  <div class="card">
    <ul class="list-group list-group-flush">
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <div style="width: 35%;">お名前</div>
        <div><%= link_to @user.name, user_path(@user),class:"btn text-secondary mb-0" %></div>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <div style="width: 35%;">チーム名</div>
        <div><%= link_to @user.team.name, team_path(@user.team),class:"btn text-secondary mb-0" %></div>
        </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <div style="width: 35%;">グループ<span class="d-none d-sm-inline">名</span></div>
        <div class="d-flex flex-wrap">
          <% if @user.user_groups.any? %>
            <% @user.user_groups.each do |user_group| %>
              <div><%= link_to user_group.group.name, group_path(user_group.group),class:"btn text-secondary mb-0" %></div>
            <% end %>
          <% else %>
            参加しているグループはありません
          <% end %>
        </div>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <div style="width: 35%;">本日の予定</div>
        <div class="d-flex flex-wrap">
          <% if @today_hiit_for_user.any? %>
            <% @today_hiit_for_user.each do |today_hiit_for_user| %>
              <%= link_to today_hiit_for_user.name, hiit_path(today_hiit_for_user),class:"btn text-secondary mb-0" %>
            <% end %>
          <% else %>
            本日の予定はありません
          <% end %>
        </div>
      </li>
    </ul>
  </div>



  <% if user_signed_in? && (current_user.admin? || current_user.id == @user.id) %>
    <div class="link-container">  
      <%= link_to "本日の詳しい予定を見る", user_user_hiits_path(@user), class:"btn text-secondary mb-0" %>
      <%= link_to "元のページに戻る", detail_user_path(@user), class:"btn text-secondary mb-0" %>
    </div>
  <% end %>
  <div class="link-container">  
    <% if user_signed_in? && current_user.id == @user.id %>
      <%= link_to "ユーザー情報を編集する", edit_user_registration_path, class:"btn text-secondary mb-0" %>
    <% end %>
    <%= link_to "ホーム画面へ戻る", root_path, class:"btn text-secondary mb-0" %>
  </div>
  <% if user_signed_in? && current_user.admin? %>
    <div class="link-container">  
      <%= link_to "#{@user.name}を削除する", user_path(@user), method: :delete, class:"btn text-secondary mb-0" %>
    </div>
  <% end %>
</main>