config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get root to: "teams#index"
  resources :teams, except: :destroy
  resources :users, only: [:show, :destroy]
  resources :users do
    member do
      get "detail"
    end
  end
  resources :menus, except: [:index]
  resources :hiits, except: [:index]
  resources :groups, except: [:index]
  resources :hiits do
    resources :groups do
      collection do
        get "new_restricted"
      end
    end
    resources :user_hiits, only: [:create]
  end
  resources :user do
    resources :user_hiits, only: [:index]
  end
end

app/views/shared/_each_user.html.erb
<% users.each do |user| %>
  <div class="pt-2">
    <% if user_signed_in? && user.id == current_user.id %>
      <%= link_to user.name, user_path(user), class:"text-secondary text-decoration-none" %>
    <% elsif user_signed_in? && current_user.admin? %>
      <%= link_to user.name, detail_user_path(user), class:"text-secondary text-decoration-none" %>
    <% elsif user_signed_in? %>
      <%= user.name %>
    <% end %>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
  <% model.errors.full_messages.each do |message| %>
    <div class="error-message">
      <%= message %>
    </div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
HiitApp ~ Heat Up Yourself ~

app/views/shared/_header.html.erb
<div class="p-3 ps-3 ps-sm-5">
  <%= link_to "HiitApp", root_path, class:"btn text-secondary fs-1" %>
</div>
<div>
  <!--ユーザーがログインしているかどうかで表示内容を変更-->
  <% unless user_signed_in? %>
  <!--ログインしていない場合-->
    <%= link_to "チームを登録する", new_team_path, class:"btn text-secondary mb-0" %>
    <%= link_to "ユーザーを登録する", new_user_registration_path, class:"btn text-secondary mb-0" %>
    <%= link_to "ログインする", new_user_session_path, class:"btn text-secondary mb-0" %>
  <!--ログインしている場合の表示-->
  <% else %>
    <div class="team-user-container">
      <div class="d-none d-sm-block">
        <%= link_to current_user.team.name, team_path(current_user.team), class:"btn text-secondary mb-0" %>
      </div>
      <div>
        <%= link_to current_user.name, user_path(current_user), class:"btn text-secondary mb-0" %>
      </div>
      <div>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"btn text-secondary mb-0" %>
      </div>
    </div>
    <div class="d-none d-sm-block">
      <% if current_user.user_groups.any? %>
        <% if current_user.user_groups.length <= 4 %>
          <% current_user.user_groups.each do |user_group| %>
            <%= link_to user_group.group.name, group_path(user_group.group), class:"btn text-secondary mb-0" %>
          <% end %>
        <% else %>
          <% 4.times do |i| %>
            <%= link_to current_user.user_groups[i].group.name, group_path(current_user.user_groups[i].group), class:"btn text-secondary mb-0" %>
          <% end %>
          <span>...</span>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>